{% set python_min = '3.9.6' %}
{% set name = "nomad-camels-driver-agilent-34401a" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_agilent_34401a-{{ version }}.tar.gz
  sha256: 3e9624616d079f3df23d027cebea08215f232e195454b090185b95f4c816c3eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pyvisa
    - pyvisa-py

test:
  imports:
    - nomad_camels_driver_agilent_34401a
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Device driver for the Agilent 34401A digital multimeter.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
